### ISSUE TITLE
Khách hàng đăng ký tài khoản để thực hiện thuê xe thông qua website

### ISSUE THREAD

**Issue by thaovy456** [k4sp3rz/DoAn_Mioto#15]
Item:Kiểm tra chức năng reset form không thành công
Pre-Condition:truy cập vào hệ thống và đang ở trang đăng ký
![image](https://github.com/user-attachments/assets/1e362ce7-c6a3-4a53-87f2-831c4adde799)

**Comment by thaovy456** [comment]
Item:khách hàng không thể chỉnh ngày sinh nhanh

**Comment by thaovy456** [comment]
Item:khách hàng không chỉnh ngày sinh nhanh

**Comment by k4sp3rz** [comment]
?
